version: '3.8'

volumes:
  portainer_data:

networks:
  mgt:
    external: yes

services:
  portainer-ce:
    image: portainer/portainer-ce:latest
    restart: unless-stopped
    ports:
      - 8000:8000
      - 9443:9443
    networks:
      - mgt
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
