version: '3.8'

networks:
  mgt:
    external: true


services:
  
  phpmyadmin:
    image: phpmyadmin:5.2.0-apache
    restart: unless-stopped
    networks:
      - mgt
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1