version: '3.8'

networks:
  pmm:
    #external: true

volumes:
  pmm_data:

services:
  
  percona:
    image: percona/pmm-server:2
    restart: unless-stopped
    networks:
      - pmm
    volumes:
      - pmm_data:/srv
    ports:
      - 8443:443
      - 8080:80