version: '3.8'

services:

  promtail:
    image: grafana/promtail
    restart: unless-stopped
    networks:
      - admin
    volumes:
      - /var/log:/var/log
      - ${PWD}/promtail/config.yaml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    ports:
      - "1514:1514"

networks:
  admin:
    external: true