version: '3.8'

volumes:
  db_data:
  db_log:

networks:
  db:
    external: yes

services:

  mariadb:
    image: mariadb:10.9.3-jammy
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/mysql
      - db_log:/var/log/mysql
      - /portainer/mariadb/rep-master/conf/50-server.cnf:/etc/mysql/mariadb.conf.d/50-server.cnf
    ports:
      - 3306:3306
    networks:
      - db
    logging:
      driver: loki
      options:
        loki-url: "http://192.168.100.101:3100/loki/api/v1/push"
    environment:
      MARIADB_ROOT_PASSWORD: password

  phpmyadmin:
    image: phpmyadmin:5.2.0-apache
    restart: unless-stopped
    networks:
      - db
    ports:
      - 8880:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mariadb